#站点设置
标题：隆哥的网站
SEO标题： SEO标题：隆哥
header-img :标头图片： img/主页-bg.jpg
描述：“这里是隆哥的网站，啥也没有
基本网址：“”基本网址：“”      # 例如，如果您的博客托管在 'host/blog' 上，则为 '/blog'# 例如，如果您的博客托管在 'host/blog' 上，则为 '/blog'# 例如，如果您的博客托管在 'host/blog' 上，则为 '/blog' '/blog'# 例如，如果您的博客托管在 'host/blog' 上，则为 '/blog' '/blog'# 例如，如果您的博客托管在 'host/blog' 上，则为 '/博客''/博客'

# 发布具有未来日期的帖子或收集文件。
未来：事实

# SNS 设置
RSS：错误
weibo_用户名： weibo_用户名： huxpro
zhihu_username       : zhihu_用户名：huxpro
github_用户名      : github_用户名：huxpro
Twitter用户名：twitter_用户名：huxpro
#facebook_用户名: huxpro
#linkedin_username：姓名-姓氏-idxxxx

#构建设置
# 从 2016 年起，GitHub Pages 不再支持“pygments”。请改用“rouge”进行突出显示。
荧光笔： 荧光笔： 胭脂
永久链接： 永久链接： 漂亮
页码：10
结论：
  [      [
    “稀疏的”，“稀疏的”，
    “ 节点模块”，“ 节点模块”，
    “Gruntfile.js”，“Gruntfile.js”，
    “寰.json”，“寰.json”，
    “读我.md”，“读我.md”，
    “README.zh.md”，  "README.zh.md" ,
  ]]
anchorjs: 
# 如果你在中国有时区问题（例如#68），请取消注释以使用此项：
#时区：CN

# 宝石
# 来自 PR#40，支持 Jekyll 3.0 的本地预览
# 确保你已经安装了这个 gem
# `$ gem 安装 jekyll-paginate`
插件: [插件：[ jekyll-paginate ] ]

# Markdown 设置
# 将 redcarpet 替换为 kramdown，
# 虽然 redcarpet 可以自动高亮代码，但是由于缺少 header-id 导致无法进入目录，所以我改用 kramdown
# 文档：http://jekyllrb.com/docs/configuration/#kramdown
markdown :降价：kramdown
克拉姆当：
  输入:   输入：GFM # 使用 Github Flavored Markdown !important# 使用 Github Flavored Markdown !important
  语法highlighter_opts：
    跨度：
      行号：false
    堵塞：
      行号：true
      起始行：1

# Disqus 设置
disqus_用户名：disqus_用户名：hux

# 网易设置
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: "UA-49627206-1"ga_track_id：“UA-49627206-1”#格式：UA-xxxxxx-xx# Format: UA-xxxxxx-xx
ga_domain: ga_domain: huangxuan.me

# Sidebar settings
sidebar: sidebar: true #是否使用侧边栏。# whether or not using Sidebar.
sidebar-about-description: "要做一个有 swag 的程序员 <br> React Team @ Meta"
sidebar-avatar: 侧边栏头像：https://github.com/Huxpro.png # 使用绝对 URL，因为它在 `/` 和 `/about/` 中都有使用://github.com/Huxpro.png # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: featured-tags: true # 是否使用Feature-Tags# whether or not using Feature-Tags
featured-condition-size: featured-condition-size: 1 # 如果标签的大小大于此条件值，则该标签将被推荐# A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends:
  [[
    { title: "乱序（Midare）",    { title: "乱序（Midare）", href: "http://mida.re/" },: "http://mida.re/" },
    { title: "Ebn Zhang",    { title: "Ebn Zhang", href: "https://ebnbin.dev/" },: "https://ebnbin.dev/" },
    { title: "Kun Qian",    { title: "坤谦", href: "http://kunq.me" },: "http://kunq.me" },
    { title: "Sherry Woo",    { title: "Sherry Woo", href: "https://sherrywoo.me/" },: "https://sherrywoo.me/" },
    { title: "SmdCn",    { title: "SmdCn", href: "http://blog.smdcn.net" },: "http://blog.smdcn.net" },
    { title: "JiyinYiyong",    { title: "吉音易用", href: "http://tiye.me/" },: "http://tiye.me/" },
    { title: "DHong Say",    { title: "DHong Say", href: "http://dhong.co" },: "http://dhong.co" },
    { title: "尹峰以为",    { title: "尹峰以为", href: "http://ingf.github.io/" },: "http://ingf.github.io/" },
  ]]
